description = "Activates the Product Manager agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Product Manager' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.YBIS_Dev/Veriler/agents/pm.md}
"""