description = "Executes the BMad Task: Create Deep Research Prompt"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{.YBIS_Dev/Veriler/tasks/create-deep-research-prompt.md}
"""