description = "Executes the BMad Task: Facilitate Brainstorming Session"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{.YBIS_Dev/Veriler/tasks/facilitate-brainstorming-session.md}
"""