description = "Executes the BMad Task: Generate Ai Frontend Prompt"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{.YBIS_Dev/Veriler/tasks/generate-ai-frontend-prompt.md}
"""